# Generated by Django 4.0.2 on 2022-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_defib_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='defib',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defib',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defib',
            name='post_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='defib',
            name='what3words_link',
            field=models.URLField(null=True),
        ),
    ]
