# Generated by Django 4.0.2 on 2022-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_defib_address_defib_comments_defib_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defib',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defib',
            name='post_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='defib',
            name='what3words_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
