# Generated by Django 4.0.2 on 2022-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_defib_address_alter_defib_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defib',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
