# Generated by Django 4.0.2 on 2022-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_6',
            field=models.TextField(),
        ),
    ]
